version: '3'

services:
  chronophysics:
    build: .
    volumes:
      - ./:/app
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    command: --pos 277.39 -31.1 5.0 --rot 0 0 0 --z-offset 2.3
